### PR TITLE
Allow more hvac combination

### LINKED ISSUE #81: Allow more heating and cooling system combinations
image

The code to do this is [here](https://github.com/NREL/hescore-hpxml/blob/master/hescorehpxml/__init__.py#L1548). We need to

- [ ] See if the translator already permits the combinations above. i.e. write unit tests for them.
- [ ] For ones where it doesn't, update the `get_hvac` method to allow that combination.

### PR DESCRIPTION
**Pull request by yzhou601**
fix #81

### CODE REVIEW

**Comment by yzhou601** [comment]
The json data output looked good after checking three data points: heating fraction/ heating capacity/ heating capacity in 17F

**Comment by nmerket** [comment]
If there are red areas that didn't throw errors that should have, can you add some code to the translation to ensure it does? Also, it looks like there are some other errors happening when I look at the CI results.

**Comment by yzhou601** [comment]
@nmerket Oh yes, that's a red area gave the error message, but it's not descriptive for the problem, I could add a check for that too, and make the right error message.

**Comment by nmerket** [comment]
@yzhou601 Nice work on this! Very thorough testing and it seems like you caught some edge cases that I hadn't before.

**Comment by yzhou601** [comment]
@nmerket No problem, tell me if there's anything else I could help with.

**Pull request merged**
