### PR TITLE
Move external_building_id to building_address element

### LINKED ISSUE #147: Move external_building_id to building_address
[In this repo](https://github.com/NREL/hescore-hpxml/blob/e5af84582b4524ad92bac0a9f153051f2d39f5eb/hescorehpxml/base.py#L879) we're placing the `external_building_id` under `building.about`. 

In the HEScore API documentation it says that it should be sent with `submit_address` which gets put in `building_address` in this tool. 

That change is easy enough to make here. @thepriestscottage @lirainer, have you been reading it out of the other location up to this point? If so, we should probably coordinate changing that. 

cc @bpark1327

### PR DESCRIPTION
**Pull request by bpark1327**
Fixes #147 

 - [x] Move the `external_building_id` code to `get_building_address`
 - [x] Change `test_external_id_passthru` and `test_external_id_extension_passthru` accordingly

### CODE REVIEW

**Review by nmerket — APPROVED** [review]
We should merge this. Wait for @lirainer to finish https://gitlab.hescloud.net/hes-api-code/hes-api-ci/-/issues/291.

**Comment by nmerket** [comment]
@bpark1327 Merge this into the `json_schema` branch to get your tests working.

**Review by nmerket — CHANGES_REQUESTED** [review]
Please update the docs to reflect the new location.

**Comment by lirainer** [comment]
LBL hes-api code has been updated. Ready to test.

**Comment by nmerket** [comment]
@lirainer Where has your change been deployed to?

**Review by nmerket — APPROVED** [review]

**Comment by lirainer** [comment]
@nmerket Not deployed yet. I was going to pull this update once you have it ready and then test locally.

**Comment by lirainer** [comment]
Then I'll have @thepriestscottage deploy the change on the PNNL system.

**Pull request merged**
